### ISSUE TITLE
 cannot log a given request because configuration has no uuid

### ISSUE THREAD

**Issue by nullpointerxyz** [yskopets/kong-plugin-kafka-log#2]
handler.lua:31: [kafka-log] cannot log a given request because configuration has no uuid, context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:8000

The latest version of Kong removes the schema's self_check property, replace by entity_checks, so generating uuid code will not be executed.

**Comment by nullpointerxyz** [comment]
the configuration  no have a key is  uuid , but  in handler.lua : 19  ,return conf.uuid  , why? 
What does this uuid do ? how to rely on validation logic in schema that automatically assigns a unique id?

**Comment by nullpointerxyz** [comment]
I konw, The latest version of Kong removes the schema's self_check property, replace by entity_checks, so generating uuid code  will not be executed.

**Comment by jaiswarvipin** [comment]
Hi,
I got the same issue, and replace the **self_check** property **entity_checks** now its throwing different error. the **entity_checks** expect table where  **self_check** accept the string.

`plugin_t.uuid = utils.uuid()`

when `plugin_t.uuid` is not having value then its throwing error.

**error is** 
`2020/05/25 19:36:54 [error] 342#0: *6256 [lua] handler.lua:31: [kafka-log] cannot log a given request because configuration has no uuid, context: ngx.timer, client: 172.18.0.1, server: 0.0.0.0:8000`

Request kindly assist on same, by sharing update the **schema.lua** or guidance will really appreciated. 

Thanks & Regards
Jaiswar Vipin Kumar R.
